/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.QuanLyMuonSach_model;


public class QuanLyMuonSach_view extends javax.swing.JFrame {
    QuanLyMuonSach_model model;
    private int maTaiKhoan;
    /**
     * Creates new form QuanLyMuonSach_view
     */
    public QuanLyMuonSach_view(int maTaiKhoan) {
        this.setTitle("Form Quản lý mượn sách");
        this.maTaiKhoan = maTaiKhoan;
        initComponents();
        this.setVisible(true);
        model = new QuanLyMuonSach_model();
        loadSach();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTimKiem = new javax.swing.JButton();
        txtTenTaiKhoan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMaTaiKhoan = new javax.swing.JTextField();
        cmbTrangThai = new javax.swing.JComboBox<>();
        txtTimKiem = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNgayTra = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMaPhieuMuon = new javax.swing.JTextField();
        lstDanhSachSach = new java.awt.List();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTraSach = new javax.swing.JTable();
        txtNgayMuon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnTao = new javax.swing.JButton();
        lblSoLuongSachMuon = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtdaGiaHan = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuTraCuu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuThongBao = new javax.swing.JMenu();
        menuSuaThongTin = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTimKiem.setText("Tìm Kiếm ");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel11.setText("Ngày Mượn:");

        cmbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa đến hạn", "Đã trả", "Đã quá hạn" }));

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        jLabel12.setText("Ngày Trả:");

        jLabel13.setText("Tên Tài Khoản:");

        jLabel9.setText("Mã Tài Khoản:");

        jLabel10.setText("Trạng Thái:");

        tblTraSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Phiếu Mượn", "Mã Bạn Đọc ", "Tên Bạn Đọc", "Ngày Mượn", "Ngày Trả", "Gia hạn", "Số Lượng Sách Mượn", "Trạng thái"
            }
        ));
        tblTraSach.setMinimumSize(new java.awt.Dimension(100, 100));
        tblTraSach.setRowHeight(30);
        tblTraSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTraSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTraSach);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Quản lý mượn sách");

        jLabel1.setText("Số lượng sách mượn : ");

        jLabel2.setText("Mã Phiếu Mượn:");

        btnTao.setText("Gia hạn sách");
        btnTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoActionPerformed(evt);
            }
        });

        lblSoLuongSachMuon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSoLuongSachMuon.setText("0");

        jLabel14.setText("Gia hạn:");

        menuTraCuu.setText("Tra cứu và tìm kiếm sách");
        menuTraCuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTraCuuMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuTraCuu);

        jMenu2.setText("Quản lý mượn sách");
        jMenuBar2.add(jMenu2);

        menuThongBao.setText("Thông báo và nhắc nhở");
        menuThongBao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuThongBaoMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuThongBao);

        menuSuaThongTin.setText("Sửa Thông Tin");
        menuSuaThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSuaThongTinMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuSuaThongTin);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(114, 114, 114))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel9))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(11, 11, 11)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMaTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                            .addComponent(txtMaPhieuMuon, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                            .addComponent(txtTenTaiKhoan)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtNgayMuon, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                                    .addComponent(txtNgayTra)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cmbTrangThai, 0, 124, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnTao, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(jLabel14))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(txtdaGiaHan)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lstDanhSachSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lblSoLuongSachMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 132, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTimKiem))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtMaPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(txtMaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(btnTao)
                                .addGap(61, 61, 61)
                                .addComponent(jLabel14)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtdaGiaHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblSoLuongSachMuon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lstDanhSachSach, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
     timKiem();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void tblTraSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTraSachMouseClicked
    layDuLieuTrongBangBanDoc();
    loadChiTietSach();
    }//GEN-LAST:event_tblTraSachMouseClicked

    private void btnTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoActionPerformed
      giaHanSach();
      loadSach();// TODO add your handling code here:
    }//GEN-LAST:event_btnTaoActionPerformed

    private void menuThongBaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuThongBaoMouseClicked
       new ThongBaoVaNhacNho_view(maTaiKhoan);
       this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_menuThongBaoMouseClicked

    private void menuSuaThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSuaThongTinMouseClicked
       new TaiKhoan_view(maTaiKhoan);
       this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_menuSuaThongTinMouseClicked

    private void menuTraCuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTraCuuMouseClicked
      new TraCuuVaTimKiem_view(maTaiKhoan);
      this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_menuTraCuuMouseClicked

    
    public void loadSach(){
    model.setMaTaiKhoan(maTaiKhoan);
    tblTraSach.setModel(model.loadSach(tblTraSach));
    System.out.println(maTaiKhoan);
    }
    public void timKiem(){
        model.setDlTimKiem(txtTimKiem.getText());
        this.tblTraSach.setModel(model.timKiem( tblTraSach));
    }
    public void loadChiTietSach(){
        lstDanhSachSach.clear();
        ArrayList<String> ds = model.layTenSachMuon(Integer.valueOf(txtMaPhieuMuon.getText()));
       for(int i = 0 ; i < ds.size(); i ++){
           lstDanhSachSach.add((i+1)+". "+ds.get(i));
       }
    }
    public void giaHanSach(){
        if(txtdaGiaHan.getText().equals("false")){
            model.giaHanPhieuMuon(Integer.valueOf(txtMaPhieuMuon.getText()));
        }
        else JOptionPane.showMessageDialog(this, "Bạn đã gia hạn rồi. \n Bạn chỉ có thể gia hạn 1 lần.");
    }
     public void layDuLieuTrongBangBanDoc(){
        int selectedRow = tblTraSach.getSelectedRow();
        if (selectedRow != -1) {
                    // Lấy dữ liệu của các cột tại dòng được chọn
                    Object maPhieuMuon = tblTraSach.getValueAt(selectedRow, 0);
                    Object maTaiKhoan = tblTraSach.getValueAt(selectedRow, 1);
                    Object tenTaiKhoan = tblTraSach.getValueAt(selectedRow, 2);
                    Object ngayMuon = tblTraSach.getValueAt(selectedRow, 3);
                    Object ngayTra = tblTraSach.getValueAt(selectedRow, 4);
                    Object daGiaHan = tblTraSach.getValueAt(selectedRow, 5);
                    Object soLuongSachMuon = tblTraSach.getValueAt(selectedRow, 6);
                    Object trangThai = tblTraSach.getValueAt(selectedRow, 7);
                      
                        this.txtMaPhieuMuon.setText(maPhieuMuon.toString());
                        this.txtMaTaiKhoan.setText(maTaiKhoan.toString());
                        this.txtTenTaiKhoan.setText(tenTaiKhoan.toString());
                        this.txtNgayMuon.setText(ngayMuon.toString());
                        this.txtNgayTra.setText(ngayTra.toString());
                        this.lblSoLuongSachMuon.setText(soLuongSachMuon.toString());
                        this.txtdaGiaHan.setText(daGiaHan.toString());
                        this.cmbTrangThai.setSelectedItem(trangThai.toString());

                } else {
                    // Nếu không có dòng nào được chọn
                    JOptionPane.showMessageDialog(this, "Chưa chọn dòng nào.");
                }
     }
     
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTao;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cmbTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSoLuongSachMuon;
    private java.awt.List lstDanhSachSach;
    private javax.swing.JMenu menuSuaThongTin;
    private javax.swing.JMenu menuThongBao;
    private javax.swing.JMenu menuTraCuu;
    private javax.swing.JTable tblTraSach;
    private javax.swing.JTextField txtMaPhieuMuon;
    private javax.swing.JTextField txtMaTaiKhoan;
    private javax.swing.JTextField txtNgayMuon;
    private javax.swing.JTextField txtNgayTra;
    private javax.swing.JTextField txtTenTaiKhoan;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtdaGiaHan;
    // End of variables declaration//GEN-END:variables
}
