/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import model.QuanLySach_model;

/**
 *
 * @author hq151
 */
public class QuanLySach_view extends javax.swing.JFrame {
        model.QuanLySach_model model;
        
    /**
     * Creates new form QuanLySach_view
     */
    public QuanLySach_view() {
        this.setTitle("Form Quản lý sách");
        initComponents();
        this.model = new QuanLySach_model();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setTitle("Quản Lý Sách");
        this.loadSach(tblQuanLySach);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQuanLySach = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnChinhSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        txtTenSach = new javax.swing.JTextField();
        txtTimKiem = new javax.swing.JTextField();
        txtNhaXuatBan = new javax.swing.JTextField();
        txtTheLoai = new javax.swing.JTextField();
        txtViTri = new javax.swing.JTextField();
        txtNamXuatBan = new javax.swing.JTextField();
        txtMaSach = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        txtNgonNgu = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuQuanLySach = new javax.swing.JMenu();
        menuQuanLyBanDoc = new javax.swing.JMenu();
        menuQuanLyPhieuViPham = new javax.swing.JMenu();
        menuQuanLyBaoCao = new javax.swing.JMenu();
        menuQuanLyMuonTra = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(1080, 700));

        tblQuanLySach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Vị trí", "Nhà xuất bản", "Thể loại", "Năm xuất bản", "Ngôn ngữ", "Số lượng"
            }
        ));
        tblQuanLySach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuanLySachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQuanLySach);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Quản lý sách");

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnChinhSua.setText("Chỉnh sửa");
        btnChinhSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChinhSuaActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã sách: ");

        jLabel3.setText("Vị trí:");

        jLabel4.setText("Tên sách: ");

        jLabel5.setText("Nhà xuất bản:");

        jLabel6.setText("Năm xuất bản:");

        jLabel7.setText("Thể loại:");

        jLabel9.setText("Số lượng:");

        jLabel10.setText("Ngôn ngữ:");

        menuQuanLySach.setText("Quản lý sách");
        menuQuanLySach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuQuanLySachMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuQuanLySach);

        menuQuanLyBanDoc.setText("Quản lý bạn đọc");
        menuQuanLyBanDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuQuanLyBanDocMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuQuanLyBanDoc);

        menuQuanLyPhieuViPham.setText("Quản lý phiếu vi phạm");
        menuQuanLyPhieuViPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuQuanLyPhieuViPhamMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuQuanLyPhieuViPham);

        menuQuanLyBaoCao.setText("Quản lý báo cáo");
        menuQuanLyBaoCao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuQuanLyBaoCaoMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuQuanLyBaoCao);

        menuQuanLyMuonTra.setText("Quản lý mượn trả");
        menuQuanLyMuonTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuQuanLyMuonTraMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuQuanLyMuonTra);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtViTri, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgonNgu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTimKiem)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnChinhSua)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(446, 446, 446)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTimKiem)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChinhSua)
                            .addComponent(btnThem)
                            .addComponent(btnXoa))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtViTri, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtTenSach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(6, 6, 6)
                                .addComponent(txtNgonNgu, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        this.themSach();
        this.loadSach(tblQuanLySach);// TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnChinhSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChinhSuaActionPerformed
        this.suaSach();
        this.loadSach(tblQuanLySach);        // TODO add your handling code here:
    }//GEN-LAST:event_btnChinhSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        this.xoaSach();
        this.loadSach(tblQuanLySach);        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblQuanLySachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuanLySachMouseClicked
       this.layDuLieuTrongBang(); // TODO add your handling code here:
    }//GEN-LAST:event_tblQuanLySachMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
       this.timKiemSach();// TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void menuQuanLySachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQuanLySachMouseClicked
     new QuanLySach_view();
     this.dispose();
     // TODO add your handling code here:
    }//GEN-LAST:event_menuQuanLySachMouseClicked

    private void menuQuanLyBanDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQuanLyBanDocMouseClicked
    new QuanLyBanDoc_view();
    this.dispose();
    }//GEN-LAST:event_menuQuanLyBanDocMouseClicked

    private void menuQuanLyPhieuViPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQuanLyPhieuViPhamMouseClicked
    new QuanLyPhieuViPham_view();
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_menuQuanLyPhieuViPhamMouseClicked

    private void menuQuanLyBaoCaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQuanLyBaoCaoMouseClicked
    new QuanLyBaoCao_view();
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_menuQuanLyBaoCaoMouseClicked

    private void menuQuanLyMuonTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQuanLyMuonTraMouseClicked
    new QuanLyMuonTra_view();
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_menuQuanLyMuonTraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySach_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySach_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySach_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySach_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLySach_view().setVisible(true);
            }
        });
    }
    
    public void loadSach(JTable jtable){
       this.tblQuanLySach.setModel( this.model.loadSach(jtable));
    }
    public void themSach(){
        this.model.setMaSach(Integer.valueOf(txtMaSach.getText()));
        this.model.setTenSach(txtTenSach.getText());
        this.model.setNamXuatBan(Integer.valueOf(txtNamXuatBan.getText()));
        this.model.setNhaXuatBan(txtNhaXuatBan.getText());
        this.model.setNgonNgu(txtNgonNgu.getText());
        this.model.setTheLoai(txtTheLoai.getText());
        this.model.setViTri(txtViTri.getText());
        this.model.setSoLuong(Integer.valueOf(txtSoLuong.getText()));
        String s = this.model.themDLSach();
    }
    public void suaSach(){
        this.model.setMaSach(Integer.valueOf(txtMaSach.getText()));
        this.model.setTenSach(txtTenSach.getText());
        this.model.setNamXuatBan(Integer.valueOf(txtNamXuatBan.getText()));
        this.model.setNhaXuatBan(txtNhaXuatBan.getText());
        this.model.setNgonNgu(txtNgonNgu.getText());
        this.model.setTheLoai(txtTheLoai.getText());
        this.model.setViTri(txtViTri.getText());
        this.model.setSoLuong(Integer.valueOf(txtSoLuong.getText()));
         String s = this.model.suaDLSach();  
         JOptionPane.showMessageDialog(this,s);
    }
     public void xoaSach(){
        this.model.setMaSach(Integer.valueOf(txtMaSach.getText()));
        String s = this.model.xoaDLSach();
        JOptionPane.showMessageDialog(this,"Xóa sách thành công\n"+s);
    }
    public void layDuLieuTrongBang(){
        int selectedRow = tblQuanLySach.getSelectedRow();
        if (selectedRow != -1) {
                    // Lấy dữ liệu của các cột tại dòng được chọn
                    Object maSach = tblQuanLySach.getValueAt(selectedRow, 0);
                    Object tenSach = tblQuanLySach.getValueAt(selectedRow, 1);
                    Object theLoai = tblQuanLySach.getValueAt(selectedRow, 2);
                    Object nhaXuatBan = tblQuanLySach.getValueAt(selectedRow, 3);
                    Object viTri = tblQuanLySach.getValueAt(selectedRow,4);
                    Object namXuatBan = tblQuanLySach.getValueAt(selectedRow, 5);
                    Object ngonNgu = tblQuanLySach.getValueAt(selectedRow, 6);
                    Object soLuong = tblQuanLySach.getValueAt(selectedRow, 7);
                       
                    // Hiển thị dữ liệu ra textbox
                    txtMaSach.setText(maSach.toString());
                    txtTenSach.setText(tenSach.toString());
                    txtViTri.setText(viTri.toString());
                    txtNgonNgu.setText(ngonNgu.toString());
                    txtNamXuatBan.setText(namXuatBan.toString());
                    txtTheLoai.setText(theLoai.toString());
                    txtSoLuong.setText(soLuong.toString());
                    txtNhaXuatBan.setText(nhaXuatBan.toString());
                    
                } else {
                    // Nếu không có dòng nào được chọn
                    JOptionPane.showMessageDialog(this, "Chưa chọn dòng nào.");
                }
        }
     public void timKiemSach(){
            this.model.setDuLieuSach(txtTimKiem.getText());
            this.tblQuanLySach.setModel(this.model.timKiem(tblQuanLySach));        
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChinhSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuQuanLyBanDoc;
    private javax.swing.JMenu menuQuanLyBaoCao;
    private javax.swing.JMenu menuQuanLyMuonTra;
    private javax.swing.JMenu menuQuanLyPhieuViPham;
    private javax.swing.JMenu menuQuanLySach;
    private javax.swing.JTable tblQuanLySach;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtNamXuatBan;
    private javax.swing.JTextField txtNgonNgu;
    private javax.swing.JTextField txtNhaXuatBan;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSach;
    private javax.swing.JTextField txtTheLoai;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtViTri;
    // End of variables declaration//GEN-END:variables
}
