/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.TaoPhieuMuon_model;

/**
 *
 * @author hq151
 */
public class taoPhieuMuon_view extends javax.swing.JFrame {
    TaoPhieuMuon_model model ;
     ArrayList<Integer> danhSachSachMuon = new ArrayList<>();
     private DefaultListModel<String> listModel = new DefaultListModel<>();
    /**
     * Creates new form taoPhieuMuon_view
     */
    public taoPhieuMuon_view() {
        this.setTitle("Form Tạo phiếu mượn");
        initComponents();
        this.setVisible(true);
        model = new TaoPhieuMuon_model();
        this.loadtaoPhieuMuon();
       this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTaoPhieuMuon = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnTimKiemBanDoc = new javax.swing.JButton();
        txtTimKiemBanDoc = new javax.swing.JTextField();
        btnTimKiemSach = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTimKiemSach = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThongTinBanDoc = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblSoLuongSachMuon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSach = new javax.swing.JList<>();
        lblMaPhieuMuon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaTaiKhoan = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNgayMuon = new javax.swing.JTextField();
        txtNgayTra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuQuanLySach = new javax.swing.JMenu();
        MenuQuanLyBanDoc = new javax.swing.JMenu();
        menuQuanLyPhieuViPham = new javax.swing.JMenu();
        menuQuanLyBaoCao = new javax.swing.JMenu();
        menuQuanLyMuonTra = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTaoPhieuMuon.setText("Lưu");
        btnTaoPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoPhieuMuonActionPerformed(evt);
            }
        });

        jButton3.setText("Hủy");

        jLabel10.setText("Tên Tài Khoản:");

        jLabel7.setText("Thông Tin Bạn Đọc");

        btnTimKiemBanDoc.setText("Tìm Kiếm ");
        btnTimKiemBanDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemBanDocActionPerformed(evt);
            }
        });

        txtTimKiemBanDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemBanDocActionPerformed(evt);
            }
        });

        btnTimKiemSach.setText("Tìm Kiếm ");
        btnTimKiemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemSachActionPerformed(evt);
            }
        });

        jLabel8.setText("Tìm Kiếm Sách");

        txtTimKiemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemSachActionPerformed(evt);
            }
        });

        tblThongTinBanDoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Tài Khoản", "Tên Tài Khoản", "SDT"
            }
        ));
        tblThongTinBanDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongTinBanDocMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblThongTinBanDoc);

        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Sách", "Tên Sách", "Số Lượng"
            }
        ));
        tblSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSach);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Tạo Phiếu mượn");

        lblSoLuongSachMuon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSoLuongSachMuon.setText("0");

        jLabel3.setText("Mã Phiếu Mượn: ");

        jScrollPane2.setViewportView(lstSach);

        lblMaPhieuMuon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaPhieuMuon.setText("0");

        jLabel2.setText("Số Lượng Sách: ");

        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });

        jLabel5.setText("Mã Tài Khoản:");

        jLabel6.setText("Ngày Trả: ");

        jLabel9.setText("Ngày Mượn:");

        btnXoa.setText("Xóa Sách");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        menuQuanLySach.setText("Quản lý sách");
        menuQuanLySach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuQuanLySachMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuQuanLySach);

        MenuQuanLyBanDoc.setText("Quản lý bạn đọc");
        MenuQuanLyBanDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuQuanLyBanDocMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuQuanLyBanDoc);

        menuQuanLyPhieuViPham.setText("Quản lý phiếu vi phạm");
        menuQuanLyPhieuViPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuQuanLyPhieuViPhamMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuQuanLyPhieuViPham);

        menuQuanLyBaoCao.setText("Quản lý báo cáo");
        menuQuanLyBaoCao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuQuanLyBaoCaoMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuQuanLyBaoCao);

        menuQuanLyMuonTra.setText("Quản lý mượn trả");
        menuQuanLyMuonTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuQuanLyMuonTraMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuQuanLyMuonTra);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(358, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTimKiemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(133, 133, 133)
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiemSach)
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTimKiemBanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnTimKiemBanDoc)
                            .addGap(0, 639, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(445, 445, 445)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(364, 364, 364))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(472, 472, 472)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnTaoPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(145, 145, 145))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(90, 90, 90)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtMaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(30, 30, 30)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(66, 66, 66)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(lblMaPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(65, 65, 65)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblSoLuongSachMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jScrollPane2))))
                            .addGap(41, 41, 41)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiemSach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(btnXoa)
                .addGap(49, 49, 49)
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addComponent(jLabel10)
                .addGap(86, 86, 86))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 105, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnTimKiemBanDoc)
                                .addComponent(txtTimKiemBanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(24, 24, 24)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSoLuongSachMuon))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(lblMaPhieuMuon))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(52, 52, 52)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTaoPhieuMuon)
                        .addComponent(jButton3))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoPhieuMuonActionPerformed
        this.luuPhieuMuon();                          // TODO add your handling code here:
    }//GEN-LAST:event_btnTaoPhieuMuonActionPerformed

    private void btnTimKiemBanDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemBanDocActionPerformed
            this.timKiemBanDoc();                     // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemBanDocActionPerformed

    private void txtTimKiemBanDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemBanDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemBanDocActionPerformed

    private void btnTimKiemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemSachActionPerformed
            this.timKiemSach();
    }//GEN-LAST:event_btnTimKiemSachActionPerformed

    private void txtTimKiemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemSachActionPerformed

    private void tblThongTinBanDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongTinBanDocMouseClicked
            this.layDuLieuTrongBangBanDoc();
    }//GEN-LAST:event_tblThongTinBanDocMouseClicked

    private void tblSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSachMouseClicked
            this.layDuLieuTrongBangSach();
    }//GEN-LAST:event_tblSachMouseClicked

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        this.xoaSach();        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void menuQuanLySachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQuanLySachMouseClicked
        new QuanLySach_view();
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_menuQuanLySachMouseClicked

    private void MenuQuanLyBanDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuQuanLyBanDocMouseClicked
        new QuanLyBanDoc_view();
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_MenuQuanLyBanDocMouseClicked

    private void menuQuanLyPhieuViPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQuanLyPhieuViPhamMouseClicked
        new QuanLyPhieuViPham_view();
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_menuQuanLyPhieuViPhamMouseClicked

    private void menuQuanLyBaoCaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQuanLyBaoCaoMouseClicked
        new QuanLyBaoCao_view();
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_menuQuanLyBaoCaoMouseClicked

    private void menuQuanLyMuonTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQuanLyMuonTraMouseClicked
        new QuanLyMuonTra_view();
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_menuQuanLyMuonTraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(taoPhieuMuon_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(taoPhieuMuon_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(taoPhieuMuon_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(taoPhieuMuon_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new taoPhieuMuon_view().setVisible(true);
            }
        });
    }
    
    public void loadtaoPhieuMuon(){
        this.lblMaPhieuMuon.setText(this.model.layMaPhieuMuon()+"");
        this.tblSach.setModel(this.model.loadSach(tblSach));
        this.tblThongTinBanDoc.setModel(this.model.loadBanDoc(tblThongTinBanDoc));
     
    }
    public void taoPhieuMuon(){
        this.model.setMaTaiKhoan(Integer.valueOf(txtMaTaiKhoan.getText()));
        this.model.setNgayMuon(txtNgayMuon.getText());
        this.model.setNgayTra(txtNgayTra.getText());
    }
    private void timKiemBanDoc(){
        this.model.setDlBanDoc(txtTimKiemBanDoc.getText());
        this.tblThongTinBanDoc.setModel(this.model.timBanDoc(tblThongTinBanDoc));
    }
    private void timKiemSach(){
        this.model.setDlSach(txtTimKiemSach.getText());
        this.tblSach.setModel(this.model.timSach(tblSach));
    }
     public void layDuLieuTrongBangBanDoc(){
        int selectedRow = tblThongTinBanDoc.getSelectedRow();
        if (selectedRow != -1) {
                    // Lấy dữ liệu của các cột tại dòng được chọn
                    Object maTaiKhoan = tblThongTinBanDoc.getValueAt(selectedRow, 0);
                    Object tenBanDoc = tblThongTinBanDoc.getValueAt(selectedRow, 1);
                    Object SDT = tblThongTinBanDoc.getValueAt(selectedRow, 2);
                       
                    // Hiển thị dữ liệu ra textbox
                    txtMaTaiKhoan.setText(maTaiKhoan.toString());
                    txtHoTen.setText(tenBanDoc.toString());
                    
                } else {
                    // Nếu không có dòng nào được chọn
                    JOptionPane.showMessageDialog(this, "Chưa chọn dòng nào.");
                }
        }
    public void layDuLieuTrongBangSach(){
        int selectedRow = tblSach.getSelectedRow();
        if (selectedRow != -1) {
                    // Lấy dữ liệu của các cột tại dòng được chọn  
                    Object maSach = tblSach.getValueAt(selectedRow, 0);  
                    Object tenSach = tblSach.getValueAt(selectedRow, 1);  
                    this.model.setSoLuongSachMuon(this.model.getSoLuongSachMuon() +1);
                    this.lblSoLuongSachMuon.setText(this.model.getSoLuongSachMuon() +" ");
                    // Hiển thị dữ liệu ra list
                   danhSachSachMuon.add(Integer.valueOf(maSach.toString()));
                  listModel.addElement(this.model.getSoLuongSachMuon()+". " +tenSach.toString());
                  lstSach.setModel(listModel);
                } else {
                    // Nếu không có dòng nào được chọn
                    JOptionPane.showMessageDialog(this, "Chưa chọn dòng nào.");
                }
     }
    public void luuPhieuMuon(){
        this.model.setMaTaiKhoan(Integer.valueOf(this.txtMaTaiKhoan.getText()));
        this.model.setNgayMuon(txtNgayMuon.getText());
        this.model.setNgayTra(txtNgayTra.getText());
        this.model.setDanhSachSachMuon(danhSachSachMuon);
        this.model.taoPhieuMuon();
        this.model.setMaPhieuMuon(Integer.valueOf(lblMaPhieuMuon.getText().trim()));
        for(int i = 0 ; i < danhSachSachMuon.size(); i++){
            model.setMaSach(danhSachSachMuon.get(i));
            this.model.luuChiTietPhieuMuon();
        }
         JOptionPane.showMessageDialog(this, "Tạo Phiếu Mượn Thành Công");
    }
    public void xoaSach(){
        int selectedIndex = lstSach.getSelectedIndex();
        if (selectedIndex != -1) { // Kiểm tra nếu có phần tử được chọn
        listModel.removeElementAt(selectedIndex);
        danhSachSachMuon.remove(selectedIndex);
        lstSach.setModel(listModel);
            
         lblSoLuongSachMuon.setText(Integer.valueOf(lblSoLuongSachMuon.getText().trim())-1+"");
          System.out.println(danhSachSachMuon.size());
        }
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuQuanLyBanDoc;
    private javax.swing.JButton btnTaoPhieuMuon;
    private javax.swing.JButton btnTimKiemBanDoc;
    private javax.swing.JButton btnTimKiemSach;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblMaPhieuMuon;
    private javax.swing.JLabel lblSoLuongSachMuon;
    private javax.swing.JList<String> lstSach;
    private javax.swing.JMenu menuQuanLyBaoCao;
    private javax.swing.JMenu menuQuanLyMuonTra;
    private javax.swing.JMenu menuQuanLyPhieuViPham;
    private javax.swing.JMenu menuQuanLySach;
    private javax.swing.JTable tblSach;
    private javax.swing.JTable tblThongTinBanDoc;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaTaiKhoan;
    private javax.swing.JTextField txtNgayMuon;
    private javax.swing.JTextField txtNgayTra;
    private javax.swing.JTextField txtTimKiemBanDoc;
    private javax.swing.JTextField txtTimKiemSach;
    // End of variables declaration//GEN-END:variables
}
