/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import model.ThongBaoNhacNho_model;

/**
 *
 * @author hq151
 */
public class ThongBaoVaNhacNho_view extends javax.swing.JFrame {
   private int maTaiKhoan;
   private ThongBaoNhacNho_model model;
    /**
     * Creates new form ThongBaoVaNhacNho_view
     */
    public ThongBaoVaNhacNho_view(int maTaiKhoan) {
        this.setTitle("Form Thông báo và nhắc nhở");
        this.maTaiKhoan = maTaiKhoan;
        initComponents();
        model = new ThongBaoNhacNho_model();
        loadMuonTra();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstQuaHan = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstMuonTra = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuTimKiem = new javax.swing.JMenu();
        menuQuanLyMuonSach = new javax.swing.JMenu();
        menuThongBao = new javax.swing.JMenu();
        menuSuaThongTin = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstQuaHan.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Không có thông báo" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstQuaHan);

        lstMuonTra.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Không có thông báo" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstMuonTra);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Thông báo sách quá hạn");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Thông báo và nhắc nhở");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("Thông báo mượn trả");

        menuTimKiem.setText("Tra cứu và tìm kiếm sách");
        menuTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTimKiemMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuTimKiem);

        menuQuanLyMuonSach.setText("Quản lý mượn sách");
        menuQuanLyMuonSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuQuanLyMuonSachMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuQuanLyMuonSach);

        menuThongBao.setText("Thông báo và nhắc nhở");
        jMenuBar2.add(menuThongBao);

        menuSuaThongTin.setText("Sửa thông tin");
        menuSuaThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSuaThongTinMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuSuaThongTin);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(146, 146, 146))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(338, 338, 338)
                    .addComponent(jLabel9)
                    .addContainerGap(384, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(389, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTimKiemMouseClicked
       new TraCuuVaTimKiem_view(maTaiKhoan);
       this.dispose();  
    }//GEN-LAST:event_menuTimKiemMouseClicked

    private void menuQuanLyMuonSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQuanLyMuonSachMouseClicked
        new QuanLyMuonSach_view(maTaiKhoan);// TODO add your handling code here:
        this.dispose();  
    }//GEN-LAST:event_menuQuanLyMuonSachMouseClicked

    private void menuSuaThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSuaThongTinMouseClicked
     new TaiKhoan_view(maTaiKhoan);
       this.dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_menuSuaThongTinMouseClicked

    
    public void loadMuonTra(){
        model.setMaTaiKhoan(maTaiKhoan);
        ArrayList<String> ds = model.dsMuonTra();
        DefaultListModel<String> ls = new DefaultListModel<>();
        String s ="Mã PM: "+ ds.get(0)+", Ngày mượn: "+ds.get(1)+" , Ngày Trả: "+ ds.get(2)+ " ,SL: "+ds.get(3);
        ls.addElement(s);
        lstMuonTra.setModel(ls);
    }
     public void loadQuaHan(){
        model.setMaTaiKhoan(maTaiKhoan);
        ArrayList<String> ds = model.dsQuaHan();
        DefaultListModel<String> ls = new DefaultListModel<>();
        String s ="Mã PM: "+ ds.get(0)+", Ngày mượn: "+ds.get(1)+" , Ngày Trả: "+ ds.get(2)+ " ,SL: "+ds.get(3);
        ls.addElement(s);
        lstQuaHan.setModel(ls);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstMuonTra;
    private javax.swing.JList<String> lstQuaHan;
    private javax.swing.JMenu menuQuanLyMuonSach;
    private javax.swing.JMenu menuSuaThongTin;
    private javax.swing.JMenu menuThongBao;
    private javax.swing.JMenu menuTimKiem;
    // End of variables declaration//GEN-END:variables
}
